In [2]:
import numpy as np

In [12]:


a = np.arange(15).reshape(3,5)
a


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [13]:
a.shape

(3, 5)

In [14]:
a.ndim

2

In [15]:
a.dtype

dtype('int64')

In [16]:
a.itemsize

8

In [5]:
#arraty transaform
a=np.array([(1,2,3),(4,5,6)])

a


array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
#exclicitly specified at sreate time
c = np.array([[1, 2], [3, 4]], dtype=complex)
c


array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [ ]:
#create

a=np.zeros((3,4))
a


array([[0., 0., 0.],
       [0., 0., 0.]])

In [17]:
c = np.empty((3,4))
c


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [23]:
b=np.arange(10,226,5)
b

array([ 10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,  65,  70,
        75,  80,  85,  90,  95, 100, 105, 110, 115, 120, 125, 130, 135,
       140, 145, 150, 155, 160, 165, 170, 175, 180, 185, 190, 195, 200,
       205, 210, 215, 220, 225])

In [29]:
#linspace
b = np.linspace(10, 226, 5)

b

array([ 10.,  64., 118., 172., 226.])

In [38]:
a=np.empty_like((3,4))

In [41]:

a=np.arange(500).reshape(10,10,5)
a

array([[[  0,   1,   2,   3,   4],
        [  5,   6,   7,   8,   9],
        [ 10,  11,  12,  13,  14],
        [ 15,  16,  17,  18,  19],
        [ 20,  21,  22,  23,  24],
        [ 25,  26,  27,  28,  29],
        [ 30,  31,  32,  33,  34],
        [ 35,  36,  37,  38,  39],
        [ 40,  41,  42,  43,  44],
        [ 45,  46,  47,  48,  49]],

       [[ 50,  51,  52,  53,  54],
        [ 55,  56,  57,  58,  59],
        [ 60,  61,  62,  63,  64],
        [ 65,  66,  67,  68,  69],
        [ 70,  71,  72,  73,  74],
        [ 75,  76,  77,  78,  79],
        [ 80,  81,  82,  83,  84],
        [ 85,  86,  87,  88,  89],
        [ 90,  91,  92,  93,  94],
        [ 95,  96,  97,  98,  99]],

       [[100, 101, 102, 103, 104],
        [105, 106, 107, 108, 109],
        [110, 111, 112, 113, 114],
        [115, 116, 117, 118, 119],
        [120, 121, 122, 123, 124],
        [125, 126, 127, 128, 129],
        [130, 131, 132, 133, 134],
        [135, 136, 137, 138, 139],
        [140, 14

In [42]:
v=np.arange(12).reshape(3,4)
v

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [47]:
# create instance of default random number generator
rg = np.random.default_rng(1)

a = np.ones((2, 3), dtype=int)
b = rg.random((2, 3))
a *= 3
b

array([[0.51182162, 0.9504637 , 0.14415961],
       [0.94864945, 0.31183145, 0.42332645]])

In [48]:
a = np.array([1, 2, 3, 4, 5, 6])
a

array([1, 2, 3, 4, 5, 6])

In [49]:
b= a[:2]
b

array([1, 2])

In [52]:
b=np.ones((2,2),dtype=int)

b

array([[1, 1],
       [1, 1]])