In [119]:
import numpy as np

import pandas as pd

from sklearn.datasets import load_digits


In [120]:
cancer = load_digits(as_frame=True)


In [121]:
dir(cancer)

['DESCR', 'data', 'feature_names', 'frame', 'images', 'target', 'target_names']

In [122]:
print(cancer.frame)

      pixel_0_0  pixel_0_1  pixel_0_2  pixel_0_3  pixel_0_4  pixel_0_5  \
0           0.0        0.0        5.0       13.0        9.0        1.0   
1           0.0        0.0        0.0       12.0       13.0        5.0   
2           0.0        0.0        0.0        4.0       15.0       12.0   
3           0.0        0.0        7.0       15.0       13.0        1.0   
4           0.0        0.0        0.0        1.0       11.0        0.0   
...         ...        ...        ...        ...        ...        ...   
1792        0.0        0.0        4.0       10.0       13.0        6.0   
1793        0.0        0.0        6.0       16.0       13.0       11.0   
1794        0.0        0.0        1.0       11.0       15.0        1.0   
1795        0.0        0.0        2.0       10.0        7.0        0.0   
1796        0.0        0.0       10.0       14.0        8.0        1.0   

      pixel_0_6  pixel_0_7  pixel_1_0  pixel_1_1  ...  pixel_6_7  pixel_7_0  \
0           0.0        0.0      

In [123]:
data = pd.DataFrame(cancer.data, columns= cancer.feature_names)

In [124]:
data.head()

pixel_0_0  pixel_0_1  pixel_0_2  pixel_0_3  pixel_0_4  pixel_0_5  \
0        0.0        0.0        5.0       13.0        9.0        1.0   
1        0.0        0.0        0.0       12.0       13.0        5.0   
2        0.0        0.0        0.0        4.0       15.0       12.0   
3        0.0        0.0        7.0       15.0       13.0        1.0   
4        0.0        0.0        0.0        1.0       11.0        0.0   

   pixel_0_6  pixel_0_7  pixel_1_0  pixel_1_1  ...  pixel_6_6  pixel_6_7  \
0        0.0        0.0        0.0        0.0  ...        0.0        0.0   
1        0.0        0.0        0.0        0.0  ...        0.0        0.0   
2        0.0        0.0        0.0        0.0  ...        5.0        0.0   
3        0.0        0.0        0.0        8.0  ...        9.0        0.0   
4        0.0        0.0        0.0        0.0  ...        0.0        0.0   

   pixel_7_0  pixel_7_1  pixel_7_2  pixel_7_3  pixel_7_4  pixel_7_5  \
0        0.0        0.0        6.0       13.0       10.0        0.0   
1        0.0        0.0        0.0       11.0       16.0       10.0   
2        0.0        0.0        0.0        3.0       11.0       16.0   
3        0.0        0.0        7.0       13.0       13.0        9.0   
4        0.0        0.0        0.0        2.0       16.0        4.0   

   pixel_7_6  pixel_7_7  
0        0.0        0.0  
1        0.0        0.0  
2        9.0        0.0  
3        0.0        0.0  
4        0.0        0.0  

[5 rows x 64 columns]

In [125]:
data.shape

(1797, 64)

In [126]:
data['target'] = cancer.target

In [127]:
data.head()

pixel_0_0  pixel_0_1  pixel_0_2  pixel_0_3  pixel_0_4  pixel_0_5  \
0        0.0        0.0        5.0       13.0        9.0        1.0   
1        0.0        0.0        0.0       12.0       13.0        5.0   
2        0.0        0.0        0.0        4.0       15.0       12.0   
3        0.0        0.0        7.0       15.0       13.0        1.0   
4        0.0        0.0        0.0        1.0       11.0        0.0   

   pixel_0_6  pixel_0_7  pixel_1_0  pixel_1_1  ...  pixel_6_7  pixel_7_0  \
0        0.0        0.0        0.0        0.0  ...        0.0        0.0   
1        0.0        0.0        0.0        0.0  ...        0.0        0.0   
2        0.0        0.0        0.0        0.0  ...        0.0        0.0   
3        0.0        0.0        0.0        8.0  ...        0.0        0.0   
4        0.0        0.0        0.0        0.0  ...        0.0        0.0   

   pixel_7_1  pixel_7_2  pixel_7_3  pixel_7_4  pixel_7_5  pixel_7_6  \
0        0.0        6.0       13.0       10.0        0.0        0.0   
1        0.0        0.0       11.0       16.0       10.0        0.0   
2        0.0        0.0        3.0       11.0       16.0        9.0   
3        0.0        7.0       13.0       13.0        9.0        0.0   
4        0.0        0.0        2.0       16.0        4.0        0.0   

   pixel_7_7  target  
0        0.0       0  
1        0.0       1  
2        0.0       2  
3        0.0       3  
4        0.0       4  

[5 rows x 65 columns]

In [128]:
print(data[data.target == 1])

      pixel_0_0  pixel_0_1  pixel_0_2  pixel_0_3  pixel_0_4  pixel_0_5  \
1           0.0        0.0        0.0       12.0       13.0        5.0   
11          0.0        0.0        0.0        0.0       14.0       13.0   
21          0.0        0.0        0.0        2.0       16.0       16.0   
42          0.0        0.0        0.0        0.0       12.0        5.0   
47          0.0        0.0        0.0        1.0       11.0        9.0   
...         ...        ...        ...        ...        ...        ...   
1752        0.0        0.0        4.0       10.0       12.0        7.0   
1757        0.0        0.0        4.0       16.0       16.0        8.0   
1760        0.0        0.0        1.0       12.0       10.0        3.0   
1766        0.0        0.0        8.0       12.0       11.0        6.0   
1774        0.0        0.0        6.0       12.0       12.0        6.0   

      pixel_0_6  pixel_0_7  pixel_1_0  pixel_1_1  ...  pixel_6_7  pixel_7_0  \
1           0.0        0.0      

In [129]:
np.unique(data.target)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [130]:
data.describe()

pixel_0_0    pixel_0_1    pixel_0_2    pixel_0_3    pixel_0_4  \
count     1797.0  1797.000000  1797.000000  1797.000000  1797.000000   
mean         0.0     0.303840     5.204786    11.835838    11.848080   
std          0.0     0.907192     4.754826     4.248842     4.287388   
min          0.0     0.000000     0.000000     0.000000     0.000000   
25%          0.0     0.000000     1.000000    10.000000    10.000000   
50%          0.0     0.000000     4.000000    13.000000    13.000000   
75%          0.0     0.000000     9.000000    15.000000    15.000000   
max          0.0     8.000000    16.000000    16.000000    16.000000   

         pixel_0_5    pixel_0_6    pixel_0_7    pixel_1_0    pixel_1_1  ...  \
count  1797.000000  1797.000000  1797.000000  1797.000000  1797.000000  ...   
mean      5.781859     1.362270     0.129661     0.005565     1.993879  ...   
std       5.666418     3.325775     1.037383     0.094222     3.196160  ...   
min       0.000000     0.000000     0.000000     0.000000     0.000000  ...   
25%       0.000000     0.000000     0.000000     0.000000     0.000000  ...   
50%       4.000000     0.000000     0.000000     0.000000     0.000000  ...   
75%      11.000000     0.000000     0.000000     0.000000     3.000000  ...   
max      16.000000    16.000000    15.000000     2.000000    16.000000  ...   

         pixel_6_7    pixel_7_0    pixel_7_1    pixel_7_2    pixel_7_3  \
count  1797.000000  1797.000000  1797.000000  1797.000000  1797.000000   
mean      0.206455     0.000556     0.279354     5.557596    12.089037   
std       0.984401     0.023590     0.934302     5.103019     4.374694   
min       0.000000     0.000000     0.000000     0.000000     0.000000   
25%       0.000000     0.000000     0.000000     1.000000    11.000000   
50%       0.000000     0.000000     0.000000     4.000000    13.000000   
75%       0.000000     0.000000     0.000000    10.000000    16.000000   
max      13.000000     1.000000     9.000000    16.000000    16.000000   

         pixel_7_4    pixel_7_5    pixel_7_6    pixel_7_7       target  
count  1797.000000  1797.000000  1797.000000  1797.000000  1797.000000  
mean     11.809126     6.764051     2.067891     0.364496     4.490818  
std       4.933947     5.900623     4.090548     1.860122     2.865304  
min       0.000000     0.000000     0.000000     0.000000     0.000000  
25%      10.000000     0.000000     0.000000     0.000000     2.000000  
50%      14.000000     6.000000     0.000000     0.000000     4.000000  
75%      16.000000    12.000000     2.000000     0.000000     7.000000  
max      16.000000    16.000000    16.000000    16.000000     9.000000  

[8 rows x 65 columns]

In [131]:
X=data
y= data.target

In [132]:
#lets convert to scaler

from sklearn.preprocessing import StandardScaler
st= StandardScaler()

In [133]:
X_scaled = st.fit_transform(X)
X_scaled.shape

(1797, 65)

In [134]:
X_scaled

array([[ 0.        , -0.33501649, -0.04308102, ..., -0.5056698 ,
        -0.19600752, -1.56774584],
       [ 0.        , -0.33501649, -1.09493684, ..., -0.5056698 ,
        -0.19600752, -1.21864556],
       [ 0.        , -0.33501649, -1.09493684, ...,  1.6951369 ,
        -0.19600752, -0.86954528],
       ...,
       [ 0.        , -0.33501649, -0.88456568, ..., -0.5056698 ,
        -0.19600752,  1.22505642],
       [ 0.        , -0.33501649, -0.67419451, ..., -0.5056698 ,
        -0.19600752,  1.5741567 ],
       [ 0.        , -0.33501649,  1.00877481, ..., -0.26113572,
        -0.19600752,  1.22505642]])

In [135]:
new_data = pd.DataFrame(X_scaled)

In [136]:
new_data.head()

0         1         2         3         4         5         6         7   \
0  0.0 -0.335016 -0.043081  0.274072 -0.664478 -0.844129 -0.409724 -0.125023   
1  0.0 -0.335016 -1.094937  0.038648  0.268751 -0.138020 -0.409724 -0.125023   
2  0.0 -0.335016 -1.094937 -1.844742  0.735366  1.097673 -0.409724 -0.125023   
3  0.0 -0.335016  0.377661  0.744919  0.268751 -0.844129 -0.409724 -0.125023   
4  0.0 -0.335016 -1.094937 -2.551014 -0.197863 -1.020657 -0.409724 -0.125023   

         8         9   ...        55        56        57        58        59  \
0 -0.059078 -0.624009  ... -0.209785 -0.023596 -0.299081  0.086719  0.208293   
1 -0.059078 -0.624009  ... -0.209785 -0.023596 -0.299081 -1.089383 -0.249010   
2 -0.059078 -0.624009  ... -0.209785 -0.023596 -0.299081 -1.089383 -2.078218   
3 -0.059078  1.879691  ... -0.209785 -0.023596 -0.299081  0.282736  0.208293   
4 -0.059078 -0.624009  ... -0.209785 -0.023596 -0.299081 -1.089383 -2.306869   

         60        61        62        63        64  
0 -0.366771 -1.146647 -0.505670 -0.196008 -1.567746  
1  0.849632  0.548561 -0.505670 -0.196008 -1.218646  
2 -0.164037  1.565686  1.695137 -0.196008 -0.869545  
3  0.241430  0.379040 -0.505670 -0.196008 -0.520445  
4  0.849632 -0.468564 -0.505670 -0.196008 -0.171345  

[5 rows x 65 columns]

In [137]:
#split 
y= data.target

from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(X_scaled,y,test_size=0.2,random_state=10)

In [138]:
X_train.shape

(1437, 65)

In [139]:
from sklearn.linear_model import LogisticRegression

lg= LogisticRegression()
lg.fit(X_train,y_train)

LogisticRegression()

In [140]:
lg.score(X_test,y_test)

0.9888888888888889

In [141]:
X_scaled.shape

(1797, 65)

In [142]:
#PCA

from sklearn.decomposition import PCA

pca = PCA(0.95) #whta it means #retain 95% of useful features
X_pca = pca.fit_transform(X)
X_pca.shape

#got only 29 on 65 redit opf unnecessary

(1797, 29)

In [143]:
X_pca

array([[ -1.11561689, -21.34068919,   9.36633735, ...,   3.69656406,
          0.66831688,   1.17754561],
       [  7.95481232,  20.661232  ,  -4.77722493, ...,   1.90722887,
          1.18374516,  -2.32086756],
       [  7.01666565,   9.87305262,  -3.19492399, ...,   4.27272598,
         -1.64759955,  -0.90489499],
       ...,
       [ 10.73240501,   7.04862571,  -5.46899338, ...,  -3.30630351,
         -2.23612987,  -3.57405265],
       [ -4.93052351, -12.24961277,  10.47395994, ...,   2.92450014,
          0.46550271,   0.84657812],
       [ -0.36160993,  -6.3284344 , -10.50926251, ...,  -2.84508498,
         -1.45065928,  -2.62912422]])

In [144]:
pca.explained_variance_ratio_

# saying my first column is capturing 14% of variation, 14% of useful variations

array([0.14793203, 0.13533877, 0.11736819, 0.08354533, 0.05760242,
       0.04997671, 0.043828  , 0.03644352, 0.03341269, 0.03073511,
       0.02374693, 0.02263179, 0.01818323, 0.01765767, 0.01457881,
       0.01404747, 0.0132791 , 0.01250013, 0.01017906, 0.00899757,
       0.00886366, 0.00811611, 0.00771277, 0.00724598, 0.00702086,
       0.00592083, 0.00572518, 0.00522757, 0.00486257])

In [145]:
#basically columns number
pca.n_components_

np.int64(29)

In [146]:
X_train,X_test,y_train,y_test = train_test_split(X_pca,y , test_size = 0.2 , random_state=30)

In [153]:
model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

LogisticRegression(max_iter=1000)

In [154]:
model.score(X_test,y_test)

0.975

In [149]:
#no of component is 2 menas only 2 main components
pca= PCA(n_components = 2)
X_pca = pca.fit_transform(X)
X_pca.shape

(1797, 2)

In [155]:
pca.explained_variance_ratio_

array([0.14793203, 0.13533877])

In [156]:
X_train, X_test,y_train,y_test = train_test_split(X_pca,y , test_size = 0.2 , random_state=30)

In [157]:
model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)
model.score(X_test, y_test)

0.6083333333333333