In [61]:
import numpy as np
import pandas as pd

from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import load_digits


In [62]:
digits=load_digits()
dir(digits)


['DESCR', 'data', 'feature_names', 'frame', 'images', 'target', 'target_names']

In [63]:
data = pd.DataFrame(digits.data, columns= digits.feature_names)
data.head()

pixel_0_0  pixel_0_1  pixel_0_2  ...  pixel_7_5  pixel_7_6  pixel_7_7
0        0.0        0.0        5.0  ...        0.0        0.0        0.0
1        0.0        0.0        0.0  ...       10.0        0.0        0.0
2        0.0        0.0        0.0  ...       16.0        9.0        0.0
3        0.0        0.0        7.0  ...        9.0        0.0        0.0
4        0.0        0.0        0.0  ...        4.0        0.0        0.0

[5 rows x 64 columns]

In [64]:
data['target'] = digits.target
data.head()

pixel_0_0  pixel_0_1  pixel_0_2  ...  pixel_7_6  pixel_7_7  target
0        0.0        0.0        5.0  ...        0.0        0.0       0
1        0.0        0.0        0.0  ...        0.0        0.0       1
2        0.0        0.0        0.0  ...        9.0        0.0       2
3        0.0        0.0        7.0  ...        0.0        0.0       3
4        0.0        0.0        0.0  ...        0.0        0.0       4

[5 rows x 65 columns]

In [65]:
from sklearn.model_selection import train_test_split

X_train , X_test, y_train, y_test = train_test_split(data.drop(['target'],axis='columns'),data.target,test_size=0.3,random_state=10)

In [66]:
lr =LogisticRegression()
lr.fit(X_train,y_train)
lr.score(X_test,y_test)


c:\Users\ghoas\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9592592592592593

In [67]:
svm = SVC()
svm.fit(X_train,y_train)
svm.score(X_test,y_test)

0.9833333333333333

In [68]:
rf = RandomForestClassifier(n_estimators=100)
rf.fit(X_train, y_train)

rf.score(X_test, y_test)

0.9685185185185186

In [88]:
from sklearn.model_selection import KFold

kf= KFold(n_splits= 10) #means 3 folds creatted


In [70]:
#supply datasets 1-9 
# divide in 3 each for each iterations


for train_index , test_index in kf.split([1,2,3,4,5,6,7,8,9]):
        print(train_index,test_index)



[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [71]:
def get_score(model,X_train,X_test,y_train,y_test):
    model.fit(X_train,y_train)
    return model.score(X_test,y_test)

get_score(LogisticRegression(),X_train,X_test,y_train,y_test)

c:\Users\ghoas\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9592592592592593

In [72]:
# USE k FOLD
 

from sklearn.model_selection import StratifiedKFold
#StartifiedKfold is simlaialr to Kflod but this will divide folds it will divide each of the csategories in uniform ways
#image dividing 3 fold for iris flower dataset and 2 folds have 2 types of flower aand 1fold have very different type of flower
#  then it might be problem using just K fold.

folds = StratifiedKFold(n_splits = 3)
folds



StratifiedKFold(n_splits=3, random_state=None, shuffle=False)

In [85]:
data.tail()


pixel_0_0  pixel_0_1  pixel_0_2  ...  pixel_7_6  pixel_7_7  target
1792        0.0        0.0        4.0  ...        0.0        0.0       9
1793        0.0        0.0        6.0  ...        0.0        0.0       0
1794        0.0        0.0        1.0  ...        0.0        0.0       8
1795        0.0        0.0        2.0  ...        0.0        0.0       9
1796        0.0        0.0       10.0  ...        1.0        0.0       8

[5 rows x 65 columns]

In [ ]:
scores_l = []  # score array to dsplay for score of logistic
scores_svm = []  # score array to dsplay for score of svm
scores_rf = []  # score array to dsplay for score of random Frest


# [3 4 5 6 7 8] [0 1 2]
# [0 1 2 6 7 8] [3 4 5]
# [0 1 2 3 4 5] [6 7 8]

for train_index, test_index in kf.split(digits.data):  # kf is kFold ()
    # print("train_index {},test_index {}".format(train_index, test_index))
    X_train, X_test, y_train, y_test = digits.data[train_index], digits.data[
        test_index], digits.target[train_index], digits.target[test_index]
    scores_l.append(get_score(LogisticRegression(),
                    X_train, X_test, y_train, y_test))
    scores_svm.append(get_score(SVC(), X_train, X_test, y_train, y_test))
    scores_rf.append(get_score(RandomForestClassifier(),
                     X_train, X_test, y_train, y_test))


print("avg of logistic {} , avg mof sVm {} , avg of Random forest {}".format(
    sum(scores_l)/len(scores_l), sum(scores_svm)/len(scores_svm),sum( scores_rf)/len(scores_rf)))

c:\Users\ghoas\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
c:\Users\ghoas\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/st

scores of logistic 0.9315176908752327 , score mof sVm 0.9732836747361887 , scores of Random forest 0.9532433271260086


In [91]:
#theres a library to slove above problem with ease

from sklearn.model_selection import cross_val_score

cross_val_score(LogisticRegression(),digits.data,digits.target)

c:\Users\ghoas\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
c:\Users\ghoas\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/st

array([0.92222222, 0.86944444, 0.94150418, 0.93871866, 0.89693593])